/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_LoggerImpl */

#ifndef _Included_org_berkelium_impl_LoggerImpl
#define _Included_org_berkelium_impl_LoggerImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_impl_LoggerImpl
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_LoggerImpl_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_LoggerImpl
 * Method:    debug
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_LoggerImpl_debug
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_berkelium_impl_LoggerImpl
 * Method:    info
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_LoggerImpl_info
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_berkelium_impl_LoggerImpl
 * Method:    warn
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_LoggerImpl_warn
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_berkelium_impl_LoggerImpl
 * Method:    error
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_LoggerImpl_error
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
