/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_HostDelegateImpl */

#ifndef _Included_org_berkelium_impl_HostDelegateImpl
#define _Included_org_berkelium_impl_HostDelegateImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_impl_HostDelegateImpl
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_HostDelegateImpl_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_HostDelegateImpl
 * Method:    onCrashed
 * Signature: (Lorg/berkelium/api/Instance;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_HostDelegateImpl_onCrashed
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_berkelium_impl_HostDelegateImpl
 * Method:    onClosed
 * Signature: (Lorg/berkelium/api/Instance;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_HostDelegateImpl_onClosed
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
