/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_InstanceImpl */

#ifndef _Included_org_berkelium_impl_InstanceImpl
#define _Included_org_berkelium_impl_InstanceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_impl_InstanceImpl
 * Method:    getRuntime
 * Signature: ()Lorg/berkelium/api/Runtime;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_InstanceImpl_getRuntime
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_InstanceImpl
 * Method:    internalUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_InstanceImpl_internalUpdate
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_InstanceImpl
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_InstanceImpl_close
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_InstanceImpl
 * Method:    getProfile
 * Signature: ()Lorg/berkelium/api/Profile;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_InstanceImpl_getProfile
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_InstanceImpl
 * Method:    getExecutable
 * Signature: ()Lorg/berkelium/api/HostExecutable;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_InstanceImpl_getExecutable
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_InstanceImpl
 * Method:    addHostDelegate
 * Signature: (Lorg/berkelium/api/HostDelegate;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_InstanceImpl_addHostDelegate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_berkelium_impl_InstanceImpl
 * Method:    removeHostDelegate
 * Signature: (Lorg/berkelium/api/HostDelegate;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_InstanceImpl_removeHostDelegate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_berkelium_impl_InstanceImpl
 * Method:    getWindowCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_berkelium_impl_InstanceImpl_getWindowCount
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_InstanceImpl
 * Method:    getWindowList
 * Signature: ()Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_InstanceImpl_getWindowList
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_InstanceImpl
 * Method:    createWindow
 * Signature: (Z)Lorg/berkelium/api/Window;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_InstanceImpl_createWindow
  (JNIEnv *, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
