/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_BerkeliumJavaImpl */

#ifndef _Included_org_berkelium_impl_BerkeliumJavaImpl
#define _Included_org_berkelium_impl_BerkeliumJavaImpl
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
