/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_TabImpl */

#ifndef _Included_org_berkelium_impl_TabImpl
#define _Included_org_berkelium_impl_TabImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_impl_TabImpl
 * Method:    getRuntime
 * Signature: ()Lorg/berkelium/api/Runtime;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_TabImpl_getRuntime
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_TabImpl
 * Method:    internalUpdate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_TabImpl_internalUpdate
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_TabImpl
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_TabImpl_close
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_TabImpl
 * Method:    sync
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_TabImpl_sync
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_TabImpl
 * Method:    getTabDelegate
 * Signature: ()Lorg/berkelium/api/TabDelegate;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_TabImpl_getTabDelegate
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_TabImpl
 * Method:    addTabDelegate
 * Signature: (Lorg/berkelium/api/TabDelegate;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_TabImpl_addTabDelegate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_berkelium_impl_TabImpl
 * Method:    removeTabDelegate
 * Signature: (Lorg/berkelium/api/TabDelegate;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_TabImpl_removeTabDelegate
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_berkelium_impl_TabImpl
 * Method:    getWindow
 * Signature: ()Lorg/berkelium/api/Window;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_TabImpl_getWindow
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_TabImpl
 * Method:    resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_TabImpl_resize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_berkelium_impl_TabImpl
 * Method:    navigateTo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_TabImpl_navigateTo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
