/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_BerkeliumJavaImpl */

#ifndef _Included_org_berkelium_impl_BerkeliumJavaImpl
#define _Included_org_berkelium_impl_BerkeliumJavaImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_impl_BerkeliumJavaImpl
 * Method:    getNativeObjectCount
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_berkelium_impl_BerkeliumJavaImpl_getNativeObjectCount
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
