/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_HostExecutableImpl */

#ifndef _Included_org_berkelium_impl_HostExecutableImpl
#define _Included_org_berkelium_impl_HostExecutableImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_impl_HostExecutableImpl
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_HostExecutableImpl_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_HostExecutableImpl
 * Method:    getRuntime
 * Signature: ()Lorg/berkelium/api/Runtime;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_HostExecutableImpl_getRuntime
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_HostExecutableImpl
 * Method:    getPath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_berkelium_impl_HostExecutableImpl_getPath
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_HostExecutableImpl
 * Method:    getVersion
 * Signature: ()Lorg/berkelium/api/HostVersion;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_HostExecutableImpl_getVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
