/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_TabDelegateImpl */

#ifndef _Included_org_berkelium_impl_TabDelegateImpl
#define _Included_org_berkelium_impl_TabDelegateImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_impl_TabDelegateImpl
 * Method:    onClosed
 * Signature: (Lorg/berkelium/api/Tab;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_TabDelegateImpl_onClosed
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_berkelium_impl_TabDelegateImpl
 * Method:    onTitleChanged
 * Signature: (Lorg/berkelium/api/Tab;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_TabDelegateImpl_onTitleChanged
  (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     org_berkelium_impl_TabDelegateImpl
 * Method:    onPaint
 * Signature: (Lorg/berkelium/api/Tab;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_TabDelegateImpl_onPaint
  (JNIEnv *, jobject, jobject);

/*
 * Class:     org_berkelium_impl_TabDelegateImpl
 * Method:    onPaintDone
 * Signature: (Lorg/berkelium/api/Tab;Lorg/berkelium/api/Rect;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_TabDelegateImpl_onPaintDone
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
