/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_HostVersionImpl */

#ifndef _Included_org_berkelium_impl_HostVersionImpl
#define _Included_org_berkelium_impl_HostVersionImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_impl_HostVersionImpl
 * Method:    getRuntime
 * Signature: ()Lorg/berkelium/api/Runtime;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_HostVersionImpl_getRuntime
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_HostVersionImpl
 * Method:    getVersionString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_berkelium_impl_HostVersionImpl_getVersionString
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_HostVersionImpl
 * Method:    getMajor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_berkelium_impl_HostVersionImpl_getMajor
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_HostVersionImpl
 * Method:    getMinor
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_berkelium_impl_HostVersionImpl_getMinor
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_HostVersionImpl
 * Method:    getBuild
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_berkelium_impl_HostVersionImpl_getBuild
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_HostVersionImpl
 * Method:    getPatch
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_berkelium_impl_HostVersionImpl_getPatch
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_HostVersionImpl
 * Method:    isMinVersion
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_berkelium_impl_HostVersionImpl_isMinVersion
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
