/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_WindowDelegateImpl */

#ifndef _Included_org_berkelium_impl_WindowDelegateImpl
#define _Included_org_berkelium_impl_WindowDelegateImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_impl_WindowDelegateImpl
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_WindowDelegateImpl_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
