/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_BerkeliumFactoryImpl */

#ifndef _Included_org_berkelium_impl_BerkeliumFactoryImpl
#define _Included_org_berkelium_impl_BerkeliumFactoryImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_impl_BerkeliumFactoryImpl
 * Method:    getDefaultRuntime
 * Signature: ()Lorg/berkelium/api/Runtime;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_BerkeliumFactoryImpl_getDefaultRuntime
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_BerkeliumFactoryImpl
 * Method:    createRuntime
 * Signature: ()Lorg/berkelium/api/Runtime;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_BerkeliumFactoryImpl_createRuntime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
