/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_ProfileImpl */

#ifndef _Included_org_berkelium_impl_ProfileImpl
#define _Included_org_berkelium_impl_ProfileImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_impl_ProfileImpl
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_ProfileImpl_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_ProfileImpl
 * Method:    getRuntime
 * Signature: ()Lorg/berkelium/api/Runtime;
 */
JNIEXPORT jobject JNICALL Java_org_berkelium_impl_ProfileImpl_getRuntime
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_ProfileImpl
 * Method:    isInUse
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_berkelium_impl_ProfileImpl_isInUse
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_ProfileImpl
 * Method:    isFound
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_berkelium_impl_ProfileImpl_isFound
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_ProfileImpl
 * Method:    isSameVersion
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_berkelium_impl_ProfileImpl_isSameVersion
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_ProfileImpl
 * Method:    isTooNew
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_berkelium_impl_ProfileImpl_isTooNew
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_ProfileImpl
 * Method:    getApplicationName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_berkelium_impl_ProfileImpl_getApplicationName
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_ProfileImpl
 * Method:    getProfilePath
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_berkelium_impl_ProfileImpl_getProfilePath
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_ProfileImpl
 * Method:    setLocked
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_ProfileImpl_setLocked
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_berkelium_impl_ProfileImpl
 * Method:    isLocked
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_berkelium_impl_ProfileImpl_isLocked
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
