/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_berkelium_impl_LogDelegateImpl */

#ifndef _Included_org_berkelium_impl_LogDelegateImpl
#define _Included_org_berkelium_impl_LogDelegateImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_berkelium_impl_LogDelegateImpl
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_LogDelegateImpl_dispose
  (JNIEnv *, jobject);

/*
 * Class:     org_berkelium_impl_LogDelegateImpl
 * Method:    log
 * Signature: (Lorg/berkelium/api/Runtime;Lorg/berkelium/api/LogSource;Lorg/berkelium/api/LogType;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_berkelium_impl_LogDelegateImpl_log
  (JNIEnv *, jobject, jobject, jobject, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
