// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BERKELIUM_BERKELIUMFACTORY_HPP_
#define BERKELIUM_BERKELIUMFACTORY_HPP_
#pragma once

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

#include "berkelium/Berkelium.hpp"

namespace Berkelium {

class BerkeliumFactory {
public:

	// Creates an HostExecutable Object representing the given executable.
	static HostExecutableRef forExecutable(const std::string& pathTo);

	// Creates an HostExecutable, the exectuable is searched through system path or system configuration (e.g. registry on windows)
	static HostExecutableRef forSystemInstalled();

	// Returns the default profile for the given application name. A profile can only be held open by one instance at the same time . An exception is thrown of the profile is already be used.
	static ProfileRef forProfile(const std::string& application);

	// As above, but instead the given profile is used.
	static ProfileRef forProfile(const std::string& application, const std::string& profile);

	// Returns a Profile object representing the given Google Chrome profile.
	static ProfileRef forChromeProfile(const std::string& profile);

	// As above, but instead the default profile is used.
	static ProfileRef forChromeProfile();

	// Creates a temporary profile that gets automatically removed after use.
	static ProfileRef createTemporaryProfile();

	// Creates a HostVersion object representing the given version string.
	static HostVersionRef forVersion(const std::string& version);

	// Creates a HostVersion object representing the given version number.
	static HostVersionRef forVersion(int32_t vMajor, int32_t vMinor, int32_t vBuild, int32_t vPatch);

	// Launches a the given berkelium host process using the given profile.
	static InstanceRef open(HostExecutableRef executable, ProfileRef profile);
};

} // namespace Berkelium

#endif // BERKELIUM_BERKELIUMFACTORY_HPP_
