// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BERKELIUM_BERKELIUMFACTORY_HPP_
#define BERKELIUM_BERKELIUMFACTORY_HPP_
#pragma once

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

#include "berkelium/Berkelium.hpp"

namespace Berkelium {

class BerkeliumFactory {
public:

	// Creates an HostExecutable Object representing the given executable.
	static HostExecutableRef forExecutable(const std::string& pathTo);

	// Creates an HostExecutable, the exectuable is searched through system path or system configuration (e.g. registry on windows)
	static HostExecutableRef forSystemInstalled();
};

} // namespace Berkelium

#endif // BERKELIUM_BERKELIUMFACTORY_HPP_
