// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BERKELIUM_HOSTEXECUTABLE_HPP_
#define BERKELIUM_HOSTEXECUTABLE_HPP_
#pragma once

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

#include "berkelium/Berkelium.hpp"

namespace Berkelium {

// Represents a reference to the executable file of the berkelium host process.
class HostExecutable {
protected:
	HostExecutable();

public:
	virtual ~HostExecutable() = 0;

	// Returns the version of this berkelium host executable.
	virtual HostVersionRef getVersion();

	// Returns the default profile for the given application name. A profile can only be held open by one instance at the same time . An exception is thrown of the profile is already be used.
	virtual ProfileRef forProfile(const std::string& application);

	// As above, but instead the given profile is used.
	virtual ProfileRef forProfile(const std::string& application, const std::string& profile);

	// Creates a temporary profile that gets automatically removed after use.
	virtual ProfileRef createTemporaryProfile();
};

} // namespace Berkelium

#endif // BERKELIUM_HOSTEXECUTABLE_HPP_
