// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BERKELIUM_TABDELEGATE_HPP_
#define BERKELIUM_TABDELEGATE_HPP_
#pragma once

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

#include "berkelium/Berkelium.hpp"

namespace Berkelium {

// Handler for events concerning tab content.
class TabDelegate {
protected:
	TabDelegate();

public:
	virtual ~TabDelegate() = 0;
	virtual void onClosed(TabRef tab) = 0;
	virtual void onTitleChanged(TabRef tab, const std::string& title) = 0;
	virtual void onPaint(TabRef tab) = 0;
	virtual void onPaintDone(TabRef tab, const Rect& rect) = 0;
};

} // namespace Berkelium

#endif // BERKELIUM_TABDELEGATE_HPP_
