// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BERKELIUM_WINDOW_HPP_
#define BERKELIUM_WINDOW_HPP_
#pragma once

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

#include "berkelium/Berkelium.hpp"

namespace Berkelium {

class Window {
protected:
	Window();

public:
	virtual ~Window() = 0;

	// Returns the current tab count.
	virtual int32_t getTabCount();

	// Returns an ordered list of all tabs in this window.
	virtual TabList getTabList();

	// Creates a new (about:blank) Tab.
	virtual TabRef createTab();

	// Move this Tab to the given index.
	virtual void moveTo(TabRef tab, int32_t index);

	// Returns true if this is a incognito window.
	virtual bool isIncognito();
};

} // namespace Berkelium

#endif // BERKELIUM_WINDOW_HPP_
