// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.api;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

// Handler for events concerning the berkelium host process.
public interface HostDelegate {

	// Called if the host process was unexpected terminated.
	void onCrashed(Instance instance);

	// Called if the host process was properly closed.
	void onClosed(Instance instance);
}
