// Copyright (c) 2013 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.api;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

// Represents a reference to the executable file of the berkelium host process.
public interface HostExecutable {

	// Returns the associated Runtime.
	Runtime getRuntime();

	// Returns the full (native) path to the berkelium host executable represented by this object.
	String getPath();

	// Returns the version of this berkelium host executable.
	HostVersion getVersion();
}
