// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.api;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

// Represents a reference to the executable file of the berkelium host process.
public interface HostExecutable {

	// Returns the version of this berkelium host executable.
	HostVersion getVersion();

	// Returns the default profile for the given application name. A profile can only be held open by one instance at the same time . An exception is thrown of the profile is already be used.
	Profile forProfile(String application);

	// As above, but instead the given profile is used.
	Profile forProfile(String application, String profile);

	// Creates a temporary profile that gets automatically removed after use.
	Profile createTemporaryProfile();
}
