// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.api;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

// Handler for log messages. LogAdapter is an abstract class with empty function definitions for all functions in LogDelegate.
public interface LogDelegate {

	// Allows the client application to handle berkelium host console messages.
	void log(Instance instance, LogType type, String message);
}
