// Copyright (c) 2013 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.api;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

public interface Tab extends BerkeliumObject  {

	// Returns the associated Runtime.
	Runtime getRuntime();

	// Closes this tab and removes it from the window.
	void close();

	// Wait until all pending Java Script Events are handled.
	void sync();

	// Add a TabDelegate to this tab.
	void addTabDelegate(TabDelegate delegate);

	// Remove a TabDelegate from this tab.
	void removeTabDelegate(TabDelegate delegate);

	// Returns the Window of this Tab.
	Window getWindow();

	// Set the size of this tab.
	void resize(int width, int height);

	// Set the URL of this tab. A new tab has the url “about:blank”.
	void navigateTo(String url);
}
