// Copyright (c) 2013 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.api;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

// Handler for events concerning tab content.
public interface TabDelegate {

	void onClosed(Tab tab);

	void onTitleChanged(Tab tab, String title);

	void onPaint(Tab tab);

	void onPaintDone(Tab tab, Rect rect);
}
