// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.api;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

public interface Window {

	// Internal Update Function
	void internalUpdate();

	// Returns the current tab count.
	int getTabCount();

	// Returns an ordered list of all tabs in this window.
	java.util.List<Tab> getTabList();

	// Creates a new (about:blank) Tab.
	Tab createTab();

	// Returns the Instance used to create this Window.
	Instance getInstance();

	// Move this Tab to the given index.
	void moveTo(Tab tab, int index);

	// Returns true if this is a incognito window.
	boolean isIncognito();
}
