#!/bin/sh
dir=`dirname $(readlink -f "$0")`

function update_ld_path()
{
if [ ! -e $dir/run ]; then
	echo "Error: berkelium host not found!"
	exit 1
fi
cd "$dir/run"
base="$dir/../chromium/src/out"
if [ -e "$base/Debug" ]; then
	base="$base/Debug"
elif [ -e "$base/Release" ]; then
	base="$base/Release"
else
	echo "$base/Debug or $base/Release not found!"
	exit 1
fi

export LD_LIBRARY_PATH="`readlink -f $base/lib.target`"
}

function berkelium_default()
{
update_ld_path
./berkelium $*
}

function berkelium_debug_gdb()
{
update_ld_path
gdb --args ./berkelium $*
}

function berkelium_debug_external()
{
echo waiting for external debugger
echo $* > ~/.berkelium-debug
while [ -e ~/.berkelium-debug ]; do
	sleep 3
done
exit 0
}

function fake()
{
gdb --args $dir/../build/run/host-fake $*
}

#
# You can create an ~/.berkeliumrc with this content:
#
# BERKELIUM_DEBUG="gdb"
#  to debug berkelium hots with gdb on command line
#
# BERKELIUM_DEBUG="external"
#  to debug berkelium host with eclipse
#  Pass --berkelium-debug=<home>/.berkelium-debug to berkelium-host
#

[ -e ~/.berkeliumrc ] && . ~/.berkeliumrc

if [ "$1" = "debug" ]; then
	berkelium_debug_gdb `cat ~/.berkelium-debug`
	rm ~/.berkelium-debug
	exit 0
fi

if [ "$1" = "debug-fake" ]; then
	fake --berkelium-debug=`echo ~/.berkelium-debug`
	rm ~/.berkelium-debug
	exit 0
fi

if [ "$BERKELIUM_DEBUG" = "gdb" ]; then
	berkelium_debug_gdb $*
	exit 0
fi

if [ "$BERKELIUM_DEBUG" = "external" ]; then
	berkelium_debug_external $*
	exit 0
fi


berkelium_default $*
