// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BERKELIUM__HPP_
#define BERKELIUM__HPP_
#pragma once

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

#include <string>
#include <memory>

namespace Berkelium {

class HostVersion;
typedef std::shared_ptr<HostVersion> HostVersionRef;

class HostExecutableFactory;
typedef std::shared_ptr<HostExecutableFactory> HostExecutableFactoryRef;

class HostExecutable;
typedef std::shared_ptr<HostExecutable> HostExecutableRef;

class Profile;
typedef std::shared_ptr<Profile> ProfileRef;

class Instance;
typedef std::shared_ptr<Instance> InstanceRef;

} // namespace Berkelium

#endif // BERKELIUM__HPP_
