// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BERKELIUM_INSTANCE_HPP_
#define BERKELIUM_INSTANCE_HPP_
#pragma once

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

#include "berkelium/Berkelium.hpp"

namespace Berkelium {

class Instance {
protected:
	inline Instance() {}
	inline virtual ~Instance() {}

public:};

} // namespace Berkelium

#endif // BERKELIUM_INSTANCE_HPP_
