// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BERKELIUM_PROFILE_HPP_
#define BERKELIUM_PROFILE_HPP_
#pragma once

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

#include <string>

namespace Berkelium {

class HostVersion;
class HostExecutableFactory;
class HostExecutable;
class Profile;
class Instance;

// Represents a berkelium profile on disk.
public interface Profile {
};

} // namespace Berkelium

#endif // BERKELIUM_PROFILE_HPP_
