// Copyright (c) 2013 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BERKELIUM_API_BERKELIUMFACTORY_HPP_
#define BERKELIUM_API_BERKELIUMFACTORY_HPP_
#pragma once

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

#include <Berkelium/API/Berkelium.hpp>

namespace Berkelium {

class BerkeliumFactory {
public:

	// Returns the default Berkelium Runtime Instance.
	static RuntimeRef getDefaultRuntime();

	// Creates an add additional Berkelium Runtime Instance with default LogDelegate.
	static RuntimeRef createRuntime();

	// Creates an add additional Berkelium Runtime Instance with given LogDelegate.
	static RuntimeRef createRuntimeWithLog(LogDelegateRef log);
};

} // namespace Berkelium

#endif // BERKELIUM_BERKELIUMFACTORY_HPP_
