// Copyright (c) 2012 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BERKELIUM_API__HPP_
#define BERKELIUM_API__HPP_
#pragma once

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

#include <string>
#include <vector>
#include <memory>
#include <cstdint>

namespace Berkelium {

enum LogType {
	// Represents the stdout stream of the berkelium host process.
	HostOut,

	// Represents the stderr stream of the berkelium host process.
	HostErr,

	// Represents debug messages of the berkelium library.
	Debug,

	// Represents error messages of the berkelium library.
	Error,

};

class HostVersion;
typedef std::shared_ptr<HostVersion> HostVersionRef;
typedef std::weak_ptr<HostVersion> HostVersionWRef;

class BerkeliumFactory;
typedef std::shared_ptr<BerkeliumFactory> BerkeliumFactoryRef;
typedef std::weak_ptr<BerkeliumFactory> BerkeliumFactoryWRef;

class HostExecutable;
typedef std::shared_ptr<HostExecutable> HostExecutableRef;
typedef std::weak_ptr<HostExecutable> HostExecutableWRef;

class Profile;
typedef std::shared_ptr<Profile> ProfileRef;
typedef std::weak_ptr<Profile> ProfileWRef;

class LogDelegate;
typedef std::shared_ptr<LogDelegate> LogDelegateRef;
typedef std::weak_ptr<LogDelegate> LogDelegateWRef;

class HostDelegate;
typedef std::shared_ptr<HostDelegate> HostDelegateRef;
typedef std::weak_ptr<HostDelegate> HostDelegateWRef;

class Instance;
typedef std::shared_ptr<Instance> InstanceRef;
typedef std::weak_ptr<Instance> InstanceWRef;

class Window;
typedef std::shared_ptr<Window> WindowRef;
typedef std::weak_ptr<Window> WindowWRef;

class WindowDelegate;
typedef std::shared_ptr<WindowDelegate> WindowDelegateRef;
typedef std::weak_ptr<WindowDelegate> WindowDelegateWRef;

class Tab;
typedef std::shared_ptr<Tab> TabRef;
typedef std::weak_ptr<Tab> TabWRef;

class TabDelegate;
typedef std::shared_ptr<TabDelegate> TabDelegateRef;
typedef std::weak_ptr<TabDelegate> TabDelegateWRef;

typedef std::vector<WindowRef> WindowList;

typedef std::vector<TabRef> TabList;

} // namespace Berkelium

#endif // BERKELIUM__HPP_
