// Copyright (c) 2013 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BERKELIUM_API_LOGGER_HPP_
#define BERKELIUM_API_LOGGER_HPP_
#pragma once

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

#include <Berkelium/API/Berkelium.hpp>

namespace Berkelium {

class Logger {
public:
	virtual std::ostream& debug() = 0;
	virtual std::ostream& info() = 0;
	virtual std::ostream& warn() = 0;
	virtual std::ostream& error() = 0;

	virtual void systemError(const std::string& error) = 0;
	virtual void systemError(const std::string& error, const std::string& arg) = 0;
protected:
	Logger();

public:
	virtual ~Logger() = 0;
	virtual void debug(const std::string& message) = 0;
	virtual void info(const std::string& message) = 0;
	virtual void warn(const std::string& message) = 0;
	virtual void error(const std::string& message) = 0;
};

} // namespace Berkelium

#endif // BERKELIUM_LOGGER_HPP_
