// Copyright (c) 2013 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef BERKELIUM_API_UPDATE_HPP_
#define BERKELIUM_API_UPDATE_HPP_
#pragma once

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

#include <Berkelium/API/Berkelium.hpp>

namespace Berkelium {

class Update {
protected:
	Update();

public:
	virtual ~Update() = 0;
	virtual void update() = 0;
};

} // namespace Berkelium

#endif // BERKELIUM_UPDATE_HPP_
