// Copyright (c) 2013 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.impl;

import org.berkelium.api.HostExecutable;
import org.berkelium.api.HostVersion;
import org.berkelium.api.Runtime;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

class HostExecutableImpl implements HostExecutable, BerkeliumObjectImpl {

	@Override
	public native void dispose();

	@Override
	public native Runtime getRuntime();

	@Override
	public native String getPath();

	@Override
	public native HostVersion getVersion();
}
