// Copyright (c) 2013 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.impl;

import org.berkelium.api.HostDelegate;
import org.berkelium.api.Instance;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

public class HostDelegateImpl implements HostDelegate, BerkeliumObject {
	private final int id = BerkeliumJavaImpl.createId();

	public int getBerkeliumId() {
		return id;
	}

	@Override
	public native void onCrashed(Instance instance);

	@Override
	public native void onClosed(Instance instance);
}
