// Copyright (c) 2013 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.impl;

import org.berkelium.api.Profile;
import org.berkelium.api.Runtime;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

public class ProfileImpl implements Profile, BerkeliumObject {
	private final int id = BerkeliumJavaImpl.createId();

	public int getBerkeliumId() {
		return id;
	}

	@Override
	public native Runtime getRuntime();

	@Override
	public native boolean isInUse();

	@Override
	public native boolean isFound();

	@Override
	public native boolean isSameVersion();

	@Override
	public native boolean isTooNew();

	@Override
	public native String getApplicationName();

	@Override
	public native String getProfilePath();

	@Override
	public native void setLocked(boolean locked);

	@Override
	public native boolean isLocked();
}
