// Copyright (c) 2013 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.impl;

import org.berkelium.api.Rect;
import org.berkelium.api.Tab;
import org.berkelium.api.TabDelegate;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

public class TabDelegateImpl implements TabDelegate, BerkeliumObjectImpl {

	@Override
	public native void dispose();

	@Override
	public native void onClosed(Tab tab);

	@Override
	public native void onTitleChanged(Tab tab, String title);

	@Override
	public native void onPaint(Tab tab);

	@Override
	public native void onPaintDone(Tab tab, Rect rect);
}
