// Copyright (c) 2013 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.impl;

import org.berkelium.api.WindowDelegate;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

public class WindowDelegateImpl implements WindowDelegate, BerkeliumObjectImpl {
	private final int id = BerkeliumJavaImpl.createId();

	public int getBerkeliumId() {
		return id;
	}

	@Override
	public native void dispose();
}
