// Copyright (c) 2013 The Berkelium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package org.berkelium.impl;

import org.berkelium.api.Instance;
import org.berkelium.api.Runtime;
import org.berkelium.api.Tab;
import org.berkelium.api.Window;

// =========================================
// WARNING:
//   THIS FILE IS AUTOMATICALLY GENERATED!
//   !! ANY CHANGES WILL BE OVERWRITTEN !!
//
// See berkelium/berkelium-api/update.sh
// =========================================

public class WindowImpl implements Window, BerkeliumObjectImpl {
	private final int id = BerkeliumJavaImpl.createId();

	public int getBerkeliumId() {
		return id;
	}

	@Override
	public native void dispose();

	@Override
	public native Runtime getRuntime();

	@Override
	public native void internalUpdate();

	@Override
	public native int getTabCount();

	@Override
	public native java.util.List<Tab> getTabList();

	@Override
	public native Tab createTab();

	@Override
	public native Instance getInstance();

	@Override
	public native void moveTo(Tab tab, int index);

	@Override
	public native boolean isIncognito();
}
