solutions = [
  { "name"        : "deps",
    "url"         : "https://src.chromium.org/chrome/releases/22.0.1229.94",
    "deps_file"   : "DEPS",
    "managed"     : True,
    "custom_deps" : {
        "src/third_party/WebKit/LayoutTests": None,
        "src/chrome/tools/test/reference_build/chrome_win": None,
        "src/chrome_frame/tools/test/reference_build/chrome_win": None,
        "src/chrome/tools/test/reference_build/chrome_linux": None,
        "src/chrome/tools/test/reference_build/chrome_mac": None,
        "src/media/test": None,
        "src/media/test/data": None,
        "src/content/test": None,
        "src/chrome/test": None,
        "src/chrome/tools/test": None,
        "src/net/data/cache_tests": None,
        "src/native_client/src/trusted/service_runtime/testdata":  None,
        "src/third_party/gles2_book": None,
        "src/third_party/sqlite/src/test": None,
        "src/chrome/test/data/extensions/api_test/permissions/nacl_enabled/bin": None,
        "src/chrome/test/data/perf/canvas_bench": None,
        "src/chrome/test/data/perf/frame_rate/content": None,
        "src/content/test/data/layout_tests/LayoutTests/fast/events": None,
        "src/content/test/data/layout_tests/LayoutTests/fast/filesystem/resources": None,
        "src/content/test/data/layout_tests/LayoutTests/fast/js/resources": None,
        "src/content/test/data/layout_tests/LayoutTests/fast/workers": None,
        "src/content/test/data/layout_tests/LayoutTests/http/tests/appcache": None,
        "src/content/test/data/layout_tests/LayoutTests/http/tests/resources": None,
        "src/content/test/data/layout_tests/LayoutTests/http/tests/websocket/tests": None,
        "src/content/test/data/layout_tests/LayoutTests/http/tests/workers": None,
        "src/content/test/data/layout_tests/LayoutTests/http/tests/xmlhttprequest": None,
        "src/content/test/data/layout_tests/LayoutTests/media": None,
        "src/content/test/data/layout_tests/LayoutTests/platform/chromium-win/fast/events": None,
        "src/content/test/data/layout_tests/LayoutTests/platform/chromium-win/fast/workers": None,
        "src/content/test/data/layout_tests/LayoutTests/platform/chromium-win/http/tests/workers": None,
        "src/content/test/data/layout_tests/LayoutTests/platform/chromium-win/storage/domstorage": None,
        "src/content/test/data/layout_tests/LayoutTests/platform/chromium/fast/events": None,
        "src/content/test/data/layout_tests/LayoutTests/platform/chromium/fast/workers": None,
        "src/content/test/data/layout_tests/LayoutTests/storage/domstorage": None,
        "src/content/test/data/layout_tests/LayoutTests/storage/indexeddb": None,
        "src/third_party/hunspell_dictionaries": None,
    },
    "safesync_url": "",
  },
]
